name: go-pr-release

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: go-pr-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install go-pr-release
        env:
          VERSION: 0.0.1
        run: |
          curl -L -o go-pr-release.tar.gz https://github.com/tomtwinkle/go-pr-release/releases/download/v${VERSION}/go-pr-release_${VERSION}_linux_amd64.tar.gz | | tar zx -C /opt
          tar -xfz go-pr-release.tar.gz

      - name: Run
        env:
          GO_PR_RELEASE_DRY_RUN: true
          GO_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO_PR_RELEASE_RELEASE: main
          GO_PR_RELEASE_DEVELOP: develop
          GO_PR_RELEASE_LABELS: release
          GO_PR_RELEASE_REVIEWERS: tomtwinkle
        run: ./go-pr-release
