name: go-pr-release

on:
  push:
    branches:
      - develop

jobs:
  test:
    name: go-pr-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install go-pr-release
        env:
          VERSION: 0.0.1
        run: curl -L https://github.com/tomtwinkle/go-pr-release/releases/download/v${VERSION}/go-pr-release_${VERSION}_linux_amd64.tar.gz | tar -xz

      - name: Run
        env:
          GO_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
          GO_PR_RELEASE_RELEASE: main                      # Required. Release Branch: Destination to be merged
          GO_PR_RELEASE_DEVELOP: develop                   # Required. Develop Branch: Merge source
          GO_PR_RELEASE_LABELS: release                    # Optional. PullRequest labels. Multiple labels can be specified, separated by `commas`
          GO_PR_RELEASE_TITLE: ""                          # Optional. specify the title of the pull request
          GO_PR_RELEASE_TEMPLATE: ".github/template.tmpl"  # Optional. Specify a template file that can be described in `go template`
          GO_PR_RELEASE_REVIEWERS: tomtwinkle              # Optional. PullRequest reviewers. Multiple reviewers can be specified, separated by `commas`
          GO_PR_RELEASE_DRY_RUN: false                     # Optional. if true, display only the results to be created without creating PullRequest
        run: ./go-pr-release
